### ISSUE TITLE
Flink application could not reach Timestream after version upgrade

### ISSUE THREAD

**Issue by PeterCsalaHbo** [awslabs/amazon-timestream-tools#146]
## Context
- We are using Flink 1.13 with `flink-connector-timestream` 0.1 and everything works fine 
- We are about to upgrade to Flink 1.15 with `flink-connector-timestream` 0.3

## Problem
- By upgrading the packages the Timestream connection can't be established
- We are receiving `EndpointDiscoveryFailedException` 
  - While we are debugging the `EndpointDiscoveryRefreshCache` and `DefaultTimestreamWriteAsyncClient`  classes we are seeing the following error
     - *It fails at this line `cachedEndpoint = this.endpointDiscoveryCache.get(key, endpointDiscoveryRequest);`*
```
software.amazon.awssdk.core.endpointdiscovery.EndpointDiscoveryFailedException: Failed when retrieving a required endpoint from AWS.

at software.amazon.awssdk.core.endpointdiscovery.EndpointDiscoveryFailedException$BuilderImpl.build(EndpointDiscoveryFailedException.java:85)
at software.amazon.awssdk.core.endpointdiscovery.EndpointDiscoveryFailedException.create(EndpointDiscoveryFailedException.java:43)
at software.amazon.awssdk.core.endpointdiscovery.EndpointDiscoveryRefreshCache.getAndJoin(EndpointDiscoveryRefreshCache.java:97)
at software.amazon.awssdk.core.endpointdiscovery.EndpointDiscoveryRefreshCache.lambda$get$0(EndpointDiscoveryRefreshCache.java:63)
at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
at software.amazon.awssdk.core.endpointdiscovery.EndpointDiscoveryRefreshCache.get(EndpointDiscoveryRefreshCache.java:63)
at software.amazon.awssdk.services.timestreamwrite.DefaultTimestreamWriteAsyncClient.writeRecords(DefaultTimestreamWriteAsyncClient.java:1717)
at com.amazonaws.samples.connectors.timestream.TimestreamSinkWriter.asyncWriteRecords(TimestreamSinkWriter.java:176)
at com.amazonaws.samples.connectors.timestream.TimestreamSinkWriter.submitRequestEntries(TimestreamSinkWriter.java:165)
at org.apache.flink.connector.base.sink.writer.AsyncSinkWriter.flush(AsyncSinkWriter.java:397)
at org.apache.flink.connector.base.sink.writer.AsyncSinkWriter.lambda$registerCallback$3(AsyncSinkWriter.java:317)
at org.apache.flink.streaming.runtime.tasks.StreamTask.invokeProcessingTimeCallback(StreamTask.java:1651)
at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$null$21(StreamTask.java:1642)
at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.runThrowing(StreamTaskActionExecutor.java:50)
at org.apache.flink.streaming.runtime.tasks.mailbox.Mail.run(Mail.java:90)
at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMailsWhenDefaultActionUnavailable(MailboxProcessor.java:338)
at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMail(MailboxProcessor.java:324)
at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:201)
at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:807)
at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:756)
at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:948)
at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:927)
at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:741)
at org.apache.flink.runtime.taskmanager.Task.run(Task.java:563)
at java.base/java.lang.Thread.run(Thread.java:834)
```
<img width="1201" alt="Screenshot 2023-06-16 at 10 52 47" src="https://github.com/awslabs/amazon-timestream-tools/assets/73163201/3035e101-2b07-42d0-9865-5e66f3be282f">

- The caused by exception is an `ApiCallAttemptTimeoutException`
```
software.amazon.awssdk.core.exception.ApiCallAttemptTimeoutException: HTTP request execution did not complete before the specified timeout configuration: 5000 millis

at software.amazon.awssdk.core.exception.ApiCallAttemptTimeoutException$BuilderImpl.build(ApiCallAttemptTimeoutException.java:88)
at software.amazon.awssdk.core.exception.ApiCallAttemptTimeoutException.create(ApiCallAttemptTimeoutException.java:38)
at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$setupAttemptTimer$5(MakeAsyncHttpRequestStage.java:259)
at software.amazon.awssdk.core.internal.http.timers.AsyncTimeoutTask.run(AsyncTimeoutTask.java:52)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
... 1 more
```

## What we have tried 1
- We have tried to provide an `endpointOverride` like this
```java
.writeClientConfig(TimestreamSinkConfig.WriteClientConfig.builder()
    .endpointOverride("https://ingest.timestream.us-east-1.amazonaws.com")
    ...
    .build())
``` 
- In case of 1.13 the resolved endpoint was `https://ingest-cell2.timestream.us-east-1.amazonaws.com`
  - We have tried that as well but it also did not work
- With the ☝️ change we just get the  `ApiCallAttemptTimeoutException` directly (not wrapped into a `EndpointDiscoveryFailedException` since they code is not calling the `EndpointDiscoveryRefreshCache`)

## What we have tried 2
- We have run an aws cli command with the exact same role as we use in the Flink app to [`describe-endpoints`](https://docs.aws.amazon.com/cli/latest/reference/timestream-write/describe-endpoints.html) and it listed cell2

## What we have tried 3 
- We tried to run locally the application and we tried to deploy it to KDA as well
  - The results were the same exception 

## What we have tried 4 
- We tried to run the sample application and it works fine. It persisted data from KDS.

##  Side-note
- It might be irrelevant from the issue perspective but we see a lots of new INFO messages like this
```none
11:32:26,148 INFO  org.apache.flink.api.java.typeutils.runtime.kryo.KryoSerializer [] - Kryo serializer scala extensions are not available
```
____
## Our `TimestreamSinkConfig`
```java
return TimestreamSinkConfig.builder()
    .maxBatchSize(config.getMaxBatchSize()) //100
    .maxBufferedRequests(config.getMaxBufferedRequests()) //5000
    .maxInFlightRequests(config.getMaxInFlightRequests()) //100
    .maxTimeInBufferMS(config.getMaxTimeInBufferMS()) //2000
    .failureHandlerConfig(
            TimestreamSinkConfig.FailureHandlerConfig.builder()
                .failProcessingOnErrorDefault(config.isFailProcessingOnErrorDefault()) //false
                .failProcessingOnRejectedRecordsException(config.isFailProcessingOnRejectedRecordsException()) //true
                .failProcessingOnValidationException(config.isFailProcessingOnValidationException()) //true
                .printFailedRequests(config.isPrintFailedRequests()) //true
            .build())
    .emitSinkMetricsToCloudWatch(true)
    .writeClientConfig(
            TimestreamSinkConfig.WriteClientConfig.builder()
                .endpointOverride("https://ingest.timestream.us-east-1.amazonaws.com/")
                .maxConcurrency(config.getMaxConnections()) //5000
                .maxErrorRetry(config.getMaxErrorRetry()) //2
                .region(config.getRegion()) //us-east-1
                .requestTimeout(Duration.ofSeconds(config.getRequestTimeoutInSecs())) //5
            .build())
.build();
```

**Comment by PeterCsalaHbo** [comment]
It seems like we have found a working solution
We had:
```xml
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>bom</artifactId>
    <version>2.17.106</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```
We had to change to
```xml
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>bom</artifactId>
    <version>2.17.203</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
<dependency>
    <groupId>software.amazon.awssdk.crt</groupId>
    <artifactId>aws-crt</artifactId>
    <version>0.16.16</version>
</dependency>
```

these are pretty old package versions so, we need to find which versions are compatible with the TS connector
_____
We were able to upgrade till `bom` 2.19.0 with `crt` 0.20.4

**Comment by dkovalenkoI** [comment]
@PeterCsalaHbo , The pull request has been created to address the reported issue. 

Thank you for your patience and valuable feedback.
